version: '3.1'


services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:${ZOOKEEPER_VERSION}
    container_name: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - "zookeeper_data:/bitnami"
    networks:
      - net
    restart: always
    
  kafka:
    image: docker.io/bitnami/kafka:${KAFKA_VERION}
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - "kafka_data:/bitnami"
    links:
      - zookeeper
    networks:
      - net
    restart: always


volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local


networks:
    net:
        external: true