version: '3.1'


services:
  postgres:
    image: docker.io/postgres:13.4
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./Postgres/custom-postgres.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - net
    restart: always


networks:
    net:
      driver: bridge