version: '3.1'


services:
  connect:
    image: quay.io/debezium/connect:${DEBEZIUM_VERSION}
    ports:
      - "8083:8083"
    links:
     - zookeeper
     - kafka
     - postgres
    environment:
      - GROUP_ID=1
      - ADVERTISED_HOST_NAME=connect
      - BOOTSTRAP_SERVERS=kafka:9092
      - CONFIG_STORAGE_TOPIC=my-connect-configs
      - OFFSET_STORAGE_TOPIC=my-connect-offsets
      - STATUS_STORAGE_TOPIC=my-connect-statuses


networks:
    net:
      driver: bridge