version: '3.9'


services:  
  postgres:
    container_name: postgres
    image: docker.io/postgres:${POSTGRES_VERSION}
    ports:
      - "5432:5432"
    networks:
      - dev_net
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    volumes:
       - ./Postgres/custom-postgres.conf:/etc/postgresql/postgresql.conf
       - ./Postgres/data:/var/lib/postgresql/data
    restart: always


networks:
  dev_net:
    driver: bridge